namespace HdRezka.Abstractions;

internal sealed record PageSnapshot(
    int Id,
    string Name,
    IReadOnlyList<string> Names,
    string? OriginalName,
    IReadOnlyList<string> OriginalNames,
    string Description,
    Uri Thumbnail,
    Uri? ThumbnailHighQuality,
    int? ReleaseYear,
    MediaFormat Format,
    MediaCategory Category,
    MediaDetails Details,
    Rating Rating,
    AccountTier AccountTier,
    PlaybackState Playback,
    IReadOnlyList<Translator> TranslationOptions,
    IReadOnlyDictionary<int, Translator> Translators,
    IReadOnlyDictionary<string, Translator> TranslatorsByName,
    IReadOnlyList<RelatedPart> OtherParts,
    IReadOnlyList<long> BookmarkFolderIds,
    string Favorites,
    SeriesInfo? InitialSeriesInfo);
